# Generated by Django 3.0.8 on 2020-08-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200805_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='building_category',
            field=models.CharField(choices=[('bachelor', '학부생활관'), ('master', '대학원생활관'), ('BK', 'BK생활관'), ('family', '가족생활관')], max_length=20, verbose_name='생활관'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='building_dong',
            field=models.CharField(choices=[('900', '900동'), ('902', '902동'), ('901', '901동'), ('904', '904동'), ('906', '906동'), ('905', '905동'), ('903', '903동')], max_length=20, verbose_name='동'),
        ),
    ]
