# Generated by Django 3.0.8 on 2020-08-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200805_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='building_dong',
            field=models.CharField(choices=[('903', '903동'), ('906', '906동'), ('900', '900동'), ('901', '901동'), ('905', '905동'), ('904', '904동'), ('902', '902동')], max_length=20, verbose_name='동'),
        ),
    ]
