# Generated by Django 2.2.6 on 2020-07-31 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200730_2044'),
        ('accounts', '0002_auto_20200731_1540'),
    ]

    operations = [
    ]
