# Generated by Django 3.0.8 on 2020-08-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='board_info1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='board_info2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
